### ISSUE TITLE
How to get `HttpRequest` from `Free[HttpF, HttpResponse]`

### ISSUE THREAD

**Issue by vitaliihonta** [pepegar/hammock#100]
Hi!
I need to know the original http request in my code just to log errors when something goes wrong.
I'm using `runTailRec` function of `Free` with the following `Monad[HttpF]`:
```scala
  implicit object HttpFMonad extends Monad[HttpF] {
    override def pure[A](x: A): HttpF[A] = Get(HttpRequest(Uri(), Map(), None)).asInstanceOf[HttpF[A]]
    override def flatMap[A, B](fa: HttpF[A])(f: A ⇒ HttpF[B]): HttpF[B] = Get(fa.req).asInstanceOf[HttpF[B]]
    override def tailRecM[A, B](a: A)(f: A ⇒ HttpF[Either[A, B]]): HttpF[B] = f(a).asInstanceOf[HttpF[B]]
  }
```
It's obvious that such monad is incorrect but `free.runTailRec.req` produces correct output:
```scala
[error] java.lang.Exception: Failed auth, 
request: HttpRequest(Uri(Some(https),Some(Authority(None,Other(portal.admixer.net),None)),/Token,Map(),None),Map(),None) 
response: HttpResponse(Status(400,Bad Request,The request contains bad syntax or cannot be fulfilled.),Map(Access-Control-Allow-Headers -> Content-Type, x-xsrf-token, X-Requested-With, Authorization, Server -> Microsoft-IIS/10.0, Access-Control-Allow-Methods -> POST, GET, OPTIONS, Expires -> -1, Content-Length -> 34, Cache-Control -> no-cache, Content-Type -> application/json;charset=UTF-8, Pragma -> no-cache, Date -> Tue, 20 Mar 2018 11:22:07 GMT, X-Powered-By -> ASP.NET, X-ApiVersion -> 1.0.6638.23204),StringEntity({"error":"unsupported_grant_type"},hammock.ContentType$$anon$2@1e498b00))
```

So the question is:
1) Are there a simple way to get original request
2) If not, should I provide such method with the code above? (hiding this peace of... bad monad!)

**Comment by pepegar** [comment]
I think that what you're trying to do (Free[HttpF, _] => HttpRequest)
is not doable, because, you cannot get an HttpF[A] out of a
Free[HttpF, A] in the first place.

What you can do if you like to stick to the Free monad pattern is
create an logging algebra like this:

```scala
sealed trait LoggingF[A]
case class Info(message: String) extends LoggingF[Unit]
```

and then compile your Free[HttpF, A] to LoggingF with something like
this:

```scala
def logNT: HttpF ~> LoggingF = λ[HttpF ~> LoggingF] { x =>
  Info(x.req)
}
```

Finally, you could implement your `LoggingF` interpreter as you wish,
for example printint to stdout:

```scala
def logIO: LoggingF ~> IO = λ[LoggingF ~> IO] { log =>
  IO(println(log.message))
}
```

**Comment by pepegar** [comment]
Or you could skip the part of interpreting your `HttpF` to `Logging` and interpret it directly to `IO`, with the print to stdout directly

**Comment by vitaliihonta** [comment]
Thanks @pepegar !
