### ISSUE TITLE
NullPointerException on NoContent (204) response

### ISSUE THREAD

**Issue by eswenson1** [pepegar/hammock#101]
I have code similar to this:

> val response = Hammock
>     .request(Method.POST,
>       uri,
>       headers,
>        Some(body))
>     .exec[IO]
>     .unsafeRunSync

where the HTTP response is 204 (No Content).  The following code in hammock.Interpreter gets a null pointer exception:

>   private def doReq(reqF: HttpF[HttpResponse])(implicit F: Sync[F]): Kleisli[F, HttpClient, HttpResponse] =
>     Kleisli { client =>
>       for {
>         req             <- getApacheRequest(reqF)
>         resp            <- F.delay(client.execute(req))
>         body            <- F.delay(responseContentToString(resp.getEntity.getContent))
>         status          <- Status.get(resp.getStatusLine.getStatusCode).pure[F]
>         responseHeaders <- resp.getAllHeaders.map(h => h.getName -> h.getValue).toMap.pure[F]
>         _               <- F.delay(EntityUtils.consume(resp.getEntity))
>       } yield HttpResponse(status, responseHeaders, new Entity.StringEntity(body))
>     }

The issue appears to be that on a NoContent HTTP response, resp.getEntity returns null.  The above code references through the null reference with resp.getEntity.getContent.

Any way to work around this?

**Comment by pepegar** [comment]
Hey @eswenson1 this should be fixed in `0.8.3`, grab it while is still hot :)

**Comment by eswenson1** [comment]
Thanks!
