### ISSUE TITLE
BasicAuth renders wrong header name

### ISSUE THREAD

**Issue by pandemonium** [pepegar/hammock#116]
Dear Hammock-crew,

Auth.BasicAuth("user", "password") produces the correct rendition of "Basic <Base64 "$user:$pass">"

But it renders the wrong header name->value-pair. It produces:

Authentication: Basic <...>

It should produce:

Authorization: Basic <...>

I have verified this using my own tests.

**Comment by pepegar** [comment]
Thanks @pandemonium,

Fixed in #118
