### ISSUE TITLE
Separate API and implementation

### ISSUE THREAD

**Issue by ipsq** [pepegar/hammock#130]
Currently, Apache HTTP Client is always included. Even when using alternative implementations. I scanned through the code and could not find a specific reason for this. Since this is a rather heavy dependency, I'm reluctant to use the library as it is right now.

**Comment by ipsq** [comment]
Sure, will look at it this afternoon! What do you want to do with the versioning? Since this would be a breaking change for some.

**Comment by pepegar** [comment]
awesome! Yeah, I think we should release a new minor after this change (`0.9.0`), since we're still in `0` as major

**Comment by pepegar** [comment]
I think it's better to provide one by default in that case, because it doesn't add any other dependency and is the only one available in that platform. What do you think?

**Comment by ipsq** [comment]
Yeah, that's fair I guess. Was just something that popped in my mind whilst I was refactoring.

**Comment by pepegar** [comment]
closed by #156 

Thanks @ipsq !

BTW, https://oss.sonatype.org/content/repositories/snapshots/com/pepegar/hammock-core_2.12/0.8.7+52-af7aee56-SNAPSHOT/ has been published (notice that it's a snapshot).  If you want you can test-drive it and if it works for you I will release a 0.9.0!
