### ISSUE TITLE
Hammock.constructHeaders does not format cookies correctly.

### ISSUE THREAD

**Issue by ddxtanx** [pepegar/hammock#205]
Looking at the current implementation of `constructHeaders` 
```
private def constructHeaders(opts: Opts) =
    opts.headers ++
        opts.cookies.map(_.map(cookie => "Set-Cookie" -> cookie.show)).getOrElse(Map()) ++
        opts.auth.map(auth => Map("Authorization" -> auth.show)).getOrElse(Map())
```
the cookie header is implemented as "Set-Cookie," which is the _server response_ cookie header, not the _request_ cookie header, which should instead be just "Cookie."

**Comment by miciek** [comment]
Thanks for reporting @ddxtanx!

**Comment by miciek** [comment]
@stoszkom Can you have a look?
