### ISSUE TITLE
Open the interpretation to more backends

### ISSUE THREAD

**Issue by pepegar** [pepegar/hammock#31]
Currently Hammock is just a wrapper over either Apache HTTP Client or XmlHTTPRequest.  We can do better by adding more clients, or at least specifying in the docs how an interpreter is implemented for any client.

**Comment by miciek** [comment]
Happy to help with that. I see that you already started Akka HTTP implementation. Any thoughts about making it generic?

**Comment by pepegar** [comment]
Hello @miciek, thanks for stepping up here!

If you're experienced with any other HTTP client and would like to create the Hammock integration, it will be more than welcome.

The core part of the integration of a new HTTP client is the `InterpTrans` trait

```scala
trait InterpTrans {

  def trans[F[_]](implicit ME: MonadError[F, Throwable]): HttpRequestF ~> F

}
```

You can see how it's implemented in the akka-http integration PR: https://github.com/pepegar/hammock/pull/45/files#diff-dc3e7a7369ff37f7b8d264c505df60e1R21

The main pain point I'm facing with the akka-http implementation is that it renders a `Future[HttpResponse]`, and we need to turn it into an `F[_] : MonadError[?[_], Throwable]: F[HttpResponse]`. The way I'm doing it right now is `Await.result` on the future, and capturing the result in the `MonadError`, but it's a bit sketchy.

I recently came across `cats-effect` which turns out to have an `IO` type. This IO has a fully featured `fromFuture[A](f: Future[A]): IO[A]` method, that is well thought and better designed. If we'd integrate `cats-effect`, we could create interpreters for all clients whose api is based on `Future`.
