### ISSUE TITLE
Apache HTTP module duplicates headers, Akka HTTP ignores them all alltogether

### ISSUE THREAD

**Issue by jac3km4** [pepegar/hammock#70]
The base, Apache HTTP intepreter adds headers twice ([here](https://github.com/pepegar/hammock/blob/master/core/jvm/src/main/scala/hammock/jvm/free/Interpreter.scala#L44) and [here](https://github.com/pepegar/hammock/blob/master/core/jvm/src/main/scala/hammock/jvm/free/Interpreter.scala#L63)). Duplicate headers are ignored by many APIs.

Then, the Akka HTTP interpreter does not add them at all.

**Comment by pepegar** [comment]
This has been fixed in #69
