### ISSUE TITLE
example is broken

### ISSUE THREAD

**Issue by antonkulaga** [pepegar/hammock#90]
Example subproject is broken and does not compile. I also cannot use .as[T] method now

**Comment by pepegar** [comment]
Hello @antonkulaga, I think you refer to `exampleJS` project, not `example`, right?

I've checked it, and it's compiling but afterwards the scalaJS linker fails with an exception regarding not finding some classes from cats-effect.

As for the `as[T]` function, it still exists but I've changed the behaviour a bit. Now you need to import `hammock.marshalling._` into scope and then call `as` just after creating the request, such in:

https://github.com/pepegar/hammock#how-does-hammock-look-in-action

and

https://github.com/pepegar/hammock/blob/master/example/src/main/scala/example/Main.scala#L20-L24

**Comment by antonkulaga** [comment]
For the as[T], I figured out the problem: in previous version I could say somerequest.exec[IO].as[MyType] while in current version the order is different: somerequest.as[MyType].exec[IO]

Regarding ScalaJS, linker worked well for me, but I get weird matching errors when calling requests https://github.com/pepegar/hammock/issues/91

**Comment by pepegar** [comment]
I think this is fixed now. Please re-open in case this persists!
