### ISSUE TITLE
Special characters are interpreted as `?` when using Hammock with Circe

### ISSUE THREAD

**Issue by kjetilbk** [pepegar/hammock#95]
Hammock's standard `ContentType` is `text/plain`, which Apache's StringEntity and ContentType maps to the encoding `ISO-8859-1`.

To support `UTF-8`, this `ContentType` needs to be `application/json`.
As Circe is used for encoding and decoding json, I have proposed a solution where `HammockEncoderForCirce` explicitly passes `application/json; charset=utf-8` as the ContentType: https://github.com/pepegar/hammock/pull/94

Does this look like a viable solution?

**Comment by pepegar** [comment]
Hello @kjetilbk !

Thanks for catching this and for the pull request. Overall it looks OK, but let me review the PR in depth.

**Comment by pepegar** [comment]
I didn't intend to close it :)

**Comment by kjetilbk** [comment]
Fix is merged: #94
